# Changes here will be overwritten by Copier
_commit: ae0e517
_src_path: gh:34j/pypackage-template-fork
add_me_as_contributor: false
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: false
open_source_license: MIT
open_with_vscode: false
package_name: tha3
project_name: Talking Head Anime from a Single Image 3
project_short_description: Python package for tha3
project_slug: tha3
run_poetry_install: false
setup_github: false
setup_pre_commit: false
setup_venv: false
venv_version: '3.10'

